# Definição do nome do serviço
spring.application.name=demo-api
# Define a URL de conexão do banco de dados, criar o banco caso ele ainda não exista e define horário do banco como UTC
spring.datasource.url=jdbc:mysql://localhost:3306/demo_db?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
# Define classe do driver JDBC a ser utilizada na conexão com o banco
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Usuário do banco de dados (o padrão dos pcs do IF é root)
spring.datasource.username=root
# Senha do usuário no MySQL (o padrão dos pcs do IF é ifsp)
spring.datasource.password=secret123
# Permite que o hibernate crie tabelas e colunas no banco de dados, sem apagar dados pré-existentes
spring.jpa.hibernate.ddl-auto=update
# Faz com que o hibernate exiba no console todas as consultas SQL geradas e executadas por ele no banco de dados
spring.jpa.show-sql=true
# Faz com que os logs de execução sobre requisições HTTP, rotas/endpoints acessados, headers e mapeamento de controlles sejam bem mais detalhados
logging.level.org.springframework.web=DEBUG
# Faz com que o Spring exiba mensagens, avisos e erros vindos gerados no código omitindo mensagens com alto nível de detalhamento
logging.level.demo=INFO